language: ruby
rvm:
- 2.3.1
- jruby-9.1.9.0
addons:
  postgresql: '9.4'
before_install:
- "export DISPLAY=:99.0"
- "sh -e /etc/init.d/xvfb start"
before_script:
- psql -c 'create database test_track_test;' -U postgres
